export const STEP_FORTH = 'STEP_FORTH';
export const STEP_BACK = 'STEP_BACK'; 
export const CHANGE_STEPPER = 'CHANGE_STEPPER';
export const RESET_STEPPER = 'RESET_STEPPER';
export const EDIT_DATA = 'EDIT_DATA';
export const REMOVE_DATA = 'REMOVE_DATA';
export const REMOVE_ALL_DATA = 'REMOVE_ALL_DATA';

export const STEP_FORTH_ASYNC = 'STEP_FORTH_ASYNC';
export const STEP_BACK_ASYNC = 'STEP_BACK_ASYNC';
export const CHANGE_STEPPER_ASYNC = 'CHANGE_STEPPER_ASYNC';
export const RESET_STEPPER_ASYNC = 'RESET_STEPPER_ASYNC';
export const EDIT_DATA_ASYNC = 'EDIT_DATA_ASYNC';
export const REMOVE_DATA_ASYNC = 'REMOVE_DATA_ASYNC';
export const REMOVE_ALL_DATA_ASYNC = 'REMOVE_ALL_DATA_ASYNC';

