export const STEP_FORTH = 'STEP_FORTH';
export const STEP_BACK = 'STEP_BACK'; 
export const RESET_STEPPER = 'RESET_STEPPER';

export const ADD_COMPLETED_STEP = 'ADD_COMPLETED_STEP';
// export const REMOVE_LAST_COMPLETED_STEP = 'REMOVE_LAST_COMPLETED_STEP';  